In [196]:
import numpy as np
import pandas as pd
import altair as alt
from vega_datasets import data

In [197]:
#data.list_datasets()

In [198]:
mpg = data('cars')
mpg

Name  Miles_per_Gallon  Cylinders  Displacement  \
0    chevrolet chevelle malibu              18.0          8         307.0   
1            buick skylark 320              15.0          8         350.0   
2           plymouth satellite              18.0          8         318.0   
3                amc rebel sst              16.0          8         304.0   
4                  ford torino              17.0          8         302.0   
..                         ...               ...        ...           ...   
401            ford mustang gl              27.0          4         140.0   
402                  vw pickup              44.0          4          97.0   
403              dodge rampage              32.0          4         135.0   
404                ford ranger              28.0          4         120.0   
405                 chevy s-10              31.0          4         119.0   

     Horsepower  Weight_in_lbs  Acceleration       Year  Origin  
0         130.0           3504          12.0 1970-01-01     USA  
1         165.0           3693          11.5 1970-01-01     USA  
2         150.0           3436          11.0 1970-01-01     USA  
3         150.0           3433          12.0 1970-01-01     USA  
4         140.0           3449          10.5 1970-01-01     USA  
..          ...            ...           ...        ...     ...  
401        86.0           2790          15.6 1982-01-01     USA  
402        52.0           2130          24.6 1982-01-01  Europe  
403        84.0           2295          11.6 1982-01-01     USA  
404        79.0           2625          18.6 1982-01-01     USA  
405        82.0           2720          19.4 1982-01-01     USA  

[406 rows x 9 columns]

In [199]:
mpg.describe()

Miles_per_Gallon   Cylinders  Displacement  Horsepower  Weight_in_lbs  \
count        398.000000  406.000000    406.000000  400.000000     406.000000   
mean          23.514573    5.475369    194.779557  105.082500    2979.413793   
std            7.815984    1.712160    104.922458   38.768779     847.004328   
min            9.000000    3.000000     68.000000   46.000000    1613.000000   
25%           17.500000    4.000000    105.000000   75.750000    2226.500000   
50%           23.000000    4.000000    151.000000   95.000000    2822.500000   
75%           29.000000    8.000000    302.000000  130.000000    3618.250000   
max           46.600000    8.000000    455.000000  230.000000    5140.000000   

       Acceleration  
count    406.000000  
mean      15.519704  
std        2.803359  
min        8.000000  
25%       13.700000  
50%       15.500000  
75%       17.175000  
max       24.800000

In [200]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406 entries, 0 to 405
Data columns (total 9 columns):
Name                406 non-null object
Miles_per_Gallon    398 non-null float64
Cylinders           406 non-null int64
Displacement        406 non-null float64
Horsepower          400 non-null float64
Weight_in_lbs       406 non-null int64
Acceleration        406 non-null float64
Year                406 non-null datetime64[ns]
Origin              406 non-null object
dtypes: datetime64[ns](1), float64(4), int64(2), object(2)
memory usage: 28.7+ KB


In [201]:
mpg = mpg.dropna()

In [202]:
chart = alt.Chart(mpg).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon'    
)

reg_line = chart + chart.transform_regression('Horsepower', 'Miles_per_Gallon').mark_line(color="red")

alt.layer(chart, reg_line).configure_axis(
    labelFontSize=14, # change axes label font size
    titleFontSize=16  # change axes title font size
)

alt.LayerChart(...)

In [203]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [204]:
#model.fit(X = mpg['Miles_per_Gallon'], y = mpg['Horsepower'])
#model.fit(X = mpg[['Miles_per_Gallon']], y = mpg['Horsepower'])
model.fit(X = mpg[['Horsepower']], y = mpg['Miles_per_Gallon'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [205]:
# slope
b_hat_sklearn = model.coef_
# y-axis intercept
a_hat_sklearn = model.intercept_

print("Slope =", b_hat_sklearn, "intercept =", a_hat_sklearn)

Slope = [-0.15784473] intercept = 39.93586102117047


In [206]:
chart = alt.Chart(mpg).mark_point().encode(
    x='Year',
    y='Miles_per_Gallon'    
)

reg_line = chart + chart.transform_regression('Year', 'Miles_per_Gallon').mark_line(color='red')

alt.layer(chart, reg_line).configure_axis(
    labelFontSize=14, # change axes label font size
    titleFontSize=16  # change axes title font size
)

alt.LayerChart(...)

# Examining the daaset with tips

In [207]:
import seaborn as sns
tips = sns.load_dataset("tips")

In [208]:
tips.head(5)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [209]:
chart = alt.Chart(tips).mark_point().encode(
    x='total_bill', 
    y='tip'
)
chart

alt.Chart(...)

In [210]:
tips['percent'] = round(tips['tip'] / tips['total_bill'], 2)

In [211]:
tips

total_bill   tip     sex smoker   day    time  size  percent
0         16.99  1.01  Female     No   Sun  Dinner     2     0.06
1         10.34  1.66    Male     No   Sun  Dinner     3     0.16
2         21.01  3.50    Male     No   Sun  Dinner     3     0.17
3         23.68  3.31    Male     No   Sun  Dinner     2     0.14
4         24.59  3.61  Female     No   Sun  Dinner     4     0.15
..          ...   ...     ...    ...   ...     ...   ...      ...
239       29.03  5.92    Male     No   Sat  Dinner     3     0.20
240       27.18  2.00  Female    Yes   Sat  Dinner     2     0.07
241       22.67  2.00    Male    Yes   Sat  Dinner     2     0.09
242       17.82  1.75    Male     No   Sat  Dinner     2     0.10
243       18.78  3.00  Female     No  Thur  Dinner     2     0.16

[244 rows x 8 columns]

In [212]:
alt.Chart(tips).mark_point().encode(
    x='total_bill', 
    y='percent'
)

alt.Chart(...)

In [213]:
model.fit(X = tips[['total_bill']], y = tips['percent'])
# slope
b_hat_sklearn = model.coef_
# y-axis intercept
a_hat_sklearn = model.intercept_

print("Slope =", b_hat_sklearn, "intercept =", a_hat_sklearn)

Slope = [-0.00229487] intercept = 0.20634878430278836


In [214]:
chart = alt.Chart(tips).mark_point().encode(
    x='total_bill', 
    y='percent'
)

reg_line = chart + chart.transform_regression('total_bill', 'percent').mark_line(color='red')

alt.layer(chart, reg_line).configure_axis(
    labelFontSize=14, # change axes label font size
    titleFontSize=16  # change axes title font size
)

alt.LayerChart(...)

In [215]:
model.predict(np.array(50).reshape(-1,1))[0]

0.09160529642038757

# Let's observe the effect of the outliers

In [216]:
tips_mod = tips[tips['percent'] < 0.3]

In [217]:
print("Original dataset", tips.shape)
print("New dataset", tips_mod.shape)

Original dataset (244, 8)
New dataset (241, 8)


In [218]:
chart1 = alt.Chart(tips_mod).mark_point().encode(
    x='total_bill', 
    y='percent'
)

reg_line1 = chart1 + chart1.transform_regression('total_bill', 'percent').mark_line(color='red')

alt.layer(chart1, reg_line1).configure_axis(
    labelFontSize=14, # change axes label font size
    titleFontSize=16  # change axes title font size
) 

alt.LayerChart(...)

In [219]:
model.fit(X = tips_mod[['total_bill']], y = tips_mod['percent'])
# slope
b_hat_sklearn = model.coef_
# y-axis intercept
a_hat_sklearn = model.intercept_

print("Slope =", b_hat_sklearn, "intercept =", a_hat_sklearn)

Slope = [-0.00169349] intercept = 0.19067245449729037


In [220]:
model.predict(np.array(50).reshape(-1,1))[0]

0.10599779187421585

In [221]:
bill = 50
tip = b_hat_sklearn[0]*bill + a_hat_sklearn
tip

0.10599779187421585

# Multiple Regression

In [222]:
predictors = tips[['total_bill', 'size']]
predictors.head()

total_bill  size
0       16.99     2
1       10.34     3
2       21.01     3
3       23.68     2
4       24.59     4

In [223]:
model.fit(X = predictors, y = tips['percent'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [224]:
# slope
b_hat_sklearn = model.coef_
# y-axis intercept
a_hat_sklearn = model.intercept_

print("Slope =", b_hat_sklearn, "intercept =", a_hat_sklearn)

Slope = [-0.00267264  0.00590989] intercept = 0.19863684355208816


In [225]:
bill = 50
party = 2
tip = b_hat_sklearn[0]*bill + b_hat_sklearn[1]*party + a_hat_sklearn
tip

0.07682461960729962

In [226]:
bill_50 = tips[tips.total_bill > 50]
bill_50

total_bill   tip   sex smoker  day    time  size  percent
170       50.81  10.0  Male    Yes  Sat  Dinner     3      0.2

In [227]:
model.predict(bill_50[['total_bill', 'size']])

array([0.08056967])

# One-hot encoder

In [228]:
tips.head()

total_bill   tip     sex smoker  day    time  size  percent
0       16.99  1.01  Female     No  Sun  Dinner     2     0.06
1       10.34  1.66    Male     No  Sun  Dinner     3     0.16
2       21.01  3.50    Male     No  Sun  Dinner     3     0.17
3       23.68  3.31    Male     No  Sun  Dinner     2     0.14
4       24.59  3.61  Female     No  Sun  Dinner     4     0.15

In [229]:
# importing one hot encoder
from sklearn.preprocessing import OneHotEncoder
# creating one hot encoder object
onehotencoder = OneHotEncoder()

In [230]:
#reshape the 1-D array to 2-D as fit_transform expects 2-D and finally fit the object
X = onehotencoder.fit_transform(tips[['day']]).toarray()
X

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],


In [231]:
from sklearn.feature_extraction import DictVectorizer

days = tips[['day']].to_dict(orient='records')
#days

encoder = DictVectorizer(sparse=False)
days_df = pd.DataFrame(
    data = encoder.fit_transform(days),
    columns = encoder.feature_names_
)
days_df

day=Fri  day=Sat  day=Sun  day=Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [232]:
tips.shape

(244, 8)

In [233]:
tips_day = pd.concat([tips, days_df], ignore_index=False, axis=1)
tips_day

total_bill   tip     sex smoker   day    time  size  percent  day=Fri  \
0         16.99  1.01  Female     No   Sun  Dinner     2     0.06      0.0   
1         10.34  1.66    Male     No   Sun  Dinner     3     0.16      0.0   
2         21.01  3.50    Male     No   Sun  Dinner     3     0.17      0.0   
3         23.68  3.31    Male     No   Sun  Dinner     2     0.14      0.0   
4         24.59  3.61  Female     No   Sun  Dinner     4     0.15      0.0   
..          ...   ...     ...    ...   ...     ...   ...      ...      ...   
239       29.03  5.92    Male     No   Sat  Dinner     3     0.20      0.0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2     0.07      0.0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2     0.09      0.0   
242       17.82  1.75    Male     No   Sat  Dinner     2     0.10      0.0   
243       18.78  3.00  Female     No  Thur  Dinner     2     0.16      0.0   

     day=Sat  day=Sun  day=Thur  
0        0.0      1.0       0.0  
1        0.0      1.0       0.0  
2        0.0      1.0       0.0  
3        0.0      1.0       0.0  
4        0.0      1.0       0.0  
..       ...      ...       ...  
239      1.0      0.0       0.0  
240      1.0      0.0       0.0  
241      1.0      0.0       0.0  
242      1.0      0.0       0.0  
243      0.0      0.0       1.0  

[244 rows x 12 columns]

In [234]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [235]:
predictors = tips_day[['total_bill', 'day=Fri', 'day=Sat', 'day=Sun', 'day=Thur']]
predictors.head()

total_bill  day=Fri  day=Sat  day=Sun  day=Thur
0       16.99      0.0      0.0      1.0       0.0
1       10.34      0.0      0.0      1.0       0.0
2       21.01      0.0      0.0      1.0       0.0
3       23.68      0.0      0.0      1.0       0.0
4       24.59      0.0      0.0      1.0       0.0

In [236]:
outcome = tips['tip']
outcome.head()

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [237]:
model.fit(predictors, outcome)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [238]:
model.coef_, model.intercept_

(array([ 0.1046728 ,  0.00755391, -0.07843209,  0.08220781, -0.01132963]),
 0.9318792081733895)

In [239]:
model.predict(predictors)

array([2.79247782, 2.09640373, 3.21326246, 3.49273883, 3.58799107,
       3.66126203, 1.93206744, 3.82769177, 2.58836587, 2.56115094,
       2.08907663, 4.7048498 , 2.62814153, 2.94320665, 2.56638458,
       3.27292595, 2.095357  , 2.71920686, 2.79038436, 3.01494036,
       2.72918363, 2.97725815, 2.50413711, 4.97964874, 2.92806194,
       2.71766962, 2.2529224 , 2.1817449 , 3.12484679, 2.91026756,
       1.85307232, 2.77419293, 2.42981943, 3.01912727, 2.71452943,
       3.37187459, 2.56066042, 2.62555756, 2.80978168, 4.12656545,
       2.53239877, 2.84167403, 2.47322579, 2.02731968, 4.19614001,
       2.92855246, 3.34096327, 4.40548561, 4.00249534, 2.90238426,
       2.32668388, 2.09117009, 4.65774704, 2.05453461, 3.68952368,
       3.05415981, 4.8320601 , 3.61785566, 2.02996935, 5.90600298,
       2.97725815, 2.29897843, 2.00694133, 2.76791256, 2.6946416 ,
       2.95527687, 2.57531462, 1.17479261, 2.97097778, 2.42458579,
       2.11161413, 2.64021175, 3.66495842, 3.4995754 , 2.39527